### ISSUE TITLE
Coros Sync

### ISSUE THREAD

**Issue by r-follador** [r-follador/CubeTrek#10]
Add the ability for users to sync their Coros watches over the Coros API.

See https://support.coros.com/hc/en-us/articles/17085887816340-Submit-an-API-Application

**Comment by r-follador** [comment]
Currently in testing mode. Authentication of clients and linking them to CubeTrek works, however data push from Coros side seems to be broken. Awaiting feedback from Coros API team. Not very responsive.

**Comment by r-follador** [comment]
Now in open testing mode with https://github.com/r-follador/CubeTrek/commit/d3299833d1fea02d8aeadb398c60acc3027829f6

To test, log into https://cubetrek.com and click on profile (https://cubetrek.com/profile). There you can connect your Coros account with Cubetrek. Test by creating a new activity using your Cronos watch and sync with your Cronos account. The new activity should appear within a couple of minutes in CubeTrek.com

**Comment by r-follador** [comment]
@megatux: would you mind testing?

**Comment by megatux** [comment]
@r-follador, amazing! I just tested it, linked the account and it downloaded all activities from 30 days ago. Looks good. Also did a small activity to test the new workouts sync. How long should I wait for it to appear in the list?

**Comment by r-follador** [comment]
@megatux thanks for testing. According to the Coros API specs, new activities should be pushed every 5 minutes. Perhaps you need to refresh your dashboard?

If it doesn't appear, I'll need to start debugging.

**Comment by r-follador** [comment]
@megatux No, should be synced even while private. Let me check the logs later today.

**Comment by r-follador** [comment]
@megatux this looks like intended behaviour. It seems CubeTrek received the FIT file, here's an excerpt from the metadata:

`"deviceName":"COROS APEX 46mm","distance":0.0,"duration":126,"elevGain":0,"endTime":1730207216`

Distance 0 indicates that there is no GPS data within the FIT file and is thus rejected.
If you have some time to spare, you can talk a walk outside for a 100 meters or so and try again.

**Comment by megatux** [comment]
@r-follador did a new activity with some + distance and it quickly appeared in the app. Thanks

**Comment by r-follador** [comment]
This has been tested by >10 users now, without any further problems. Closed
