### ISSUE TITLE
Considerations of sensitive data

### ISSUE THREAD

**Issue by bombsimon** [r-follador/CubeTrek#3]
Thanks for this super cool project! Really appreciated and I would consider sponsoring (or contributing).

I'm eager to get started with connecting my services but I quickly glanced over the code since it is open (which is a huge plus for me). I'm not super confident around Java but it looks like the way access tokens to third party services are handled is a bit naive. One could argue that the access token is not _as_ sensitive as the access token secret since you need both in an oAuth 1.0 flow but I would still say it's reasonable to consider the access token as sensitive data, even if it's not as _secret_.

First of all I see that you're logging this data in plaintext in several places, f.ex.

https://github.com/r-follador/CubeTrek/blob/b0f6f3cc9a0aae478f54c8a07495fe22906d1415/src/main/java/com/cubetrek/upload/garminconnect/GarminconnectController.java#L109-L109

https://github.com/r-follador/CubeTrek/blob/b0f6f3cc9a0aae478f54c8a07495fe22906d1415/src/main/java/com/cubetrek/upload/garminconnect/GarminNewDeregistrationEventListener.java#L33

For the managed version we don't know where these end up or what happens with those logs.

Second it looks like the access tokens and access token secrets are stored as plaintext in the database: https://github.com/r-follador/CubeTrek/blob/b0f6f3cc9a0aae478f54c8a07495fe22906d1415/src/main/java/com/cubetrek/upload/garminconnect/GarminconnectController.java#L97-L102

From what I can tell, nothing happens between when the data is retrieved  and when it gets stored in the database. Same goes for `findByGarminUseraccesstoken` where we can take the plaintext token and lookup a user.

I think it would be a good idea to get rid of the logging of sensitive data and if you want to get debug data logging the first few bytes should be enough to determine if you got a token or not. Second I think using a symmetric key to encrypt your data before storing it would be strongly preferred. This way you reduce the risk of leaking tokens (credentials) to third party services if your database gets compromised.

It's not clear how the application is hosted but storing the key outside the application and database and feeding it on startup with something like an environment variable or secret manager would probably be a good idea.

Oh, and if I misinterpreted anything or made wrong assumptions about this, sorry for the noise! If not, do you think this change makes sense?

**Comment by r-follador** [comment]
Thanks, @bombsimon, for looking into this. This is exactly the beauty of open source to review such as issues. I don't think you misinterpreted anything, some clarifications regarding your points:

- I completely agree that it's not necessary to log the userAccessToken upon successful registration. I will trim the token to a couple of chars for output for logging purposes.
- Logging files are kept locally on the server (a Hetzner instance hosted in Germany) and discarded after 30 days
- The UserAccessToken and UserAccessSecret is required to download the FIT file from Garmin upon receiving a ping. As you correctly mention there is a OAuth flow required, which in turn depends requires the CubeTrek specific Key and Secret. This Key/Secret pair is indeed stored in the application-secrets.properties file (basically the environment variables for the Spring Boot application). So to make use of the UserAccessToken/UserAccessSecret an attacker needs the Key/Secret pair.

I suggest to follow your recommendation as follows: use a symmetric key to encrypt the UserAccessSecret, the UserAccessToken can be left in plain text in my opinion as it makes look ups simpler and I don't believe there's a benefit to encrypt both.
What do you think?

**Comment by bombsimon** [comment]
Thanks for looking in to this!

To be honest this ticket made me question my knowledge about oAuth 1.0 flow since I've mostly been in touch with oAuth 2.0 and OIDC. I'm not sure my original comment regarding what's more sensitive is correct.

I tried to quickly skim through [RFC 5849](https://datatracker.ietf.org/doc/html/rfc5849#section-3.4) and looking at the different signatures to see what parts are needed for which signing type. I don't know which one Garmin uses but I also had a quick look at [`oauth.signpost.OAuthConsumer`](https://github.com/mttkay/signpost/blob/master/signpost-core/src/main/java/oauth/signpost/OAuthConsumer.java) that you're using.

I did some testing with [Flicker's API](https://www.flickr.com/services/api/auth.oauth.html) that also uses oAuth 1.0 and either they're not following the RFC or they use a method that allows that but after I obtain an access token I can do authorized requests to their API without the consumer secret or access token secret.

Either way, I trust your judgement here regarding what should be encrypted and not. To me it sounds easy enough to encrypt both access token _and_ access token secret. When you get callbacks for Garmin you can just encrypt the access token and do the lookup with that value. But of course you should decide what you think makes most sense here!

So all and all I think your plan sounds reasonable. Again, thanks for addressing this issue and great work with CubeTrek!

**Comment by r-follador** [comment]
Implemented in [latest release](https://github.com/r-follador/CubeTrek/releases/tag/v5.2).

GarminUserAccessTokenKey and PolarUserAccessToken are symmetrically encrypted by AES and a key stored in application-secrets.properties.

Existing tokens on the CubeTrek.com database are encrypted as well.
