### ISSUE TITLE
Strava auto sync

### ISSUE THREAD

**Issue by megatux** [r-follador/CubeTrek#4]
Great project!
I consider this a must. Strava is, by far, the biggest activity site. The download method is sub-optimal, to say the least.

**Comment by r-follador** [comment]
This is likely against the [Strava API](https://www.strava.com/legal/api) agreement, remember the Relive story a couple years ago.

> You may not create an application that competes with or merely replicates Strava.

**Comment by megatux** [comment]
hmm didn't know that. There are a lot of other platforms I use that extracts activities from Strava and do similar stuff. Anyway, Coros would work for me, too :)
